import re
from playwright.sync_api import Page, expect


def test_example(page: Page) -> None:
    page.goto("https://demoqa.com/")
    page.locator("div:nth-child(2) > div > .avatar > svg").click()
    page.get_by_text("Practice Form").click()
    page.get_by_role("textbox", name="First Name").click()
    page.get_by_role("textbox", name="First Name").fill("oscar")
    page.get_by_role("textbox", name="Last Name").click()
    page.get_by_role("textbox", name="Last Name").fill("chantre")
    page.get_by_role("textbox", name="name@example.com").click()
    page.get_by_role("textbox", name="name@example.com").fill("odchantre")
    page.get_by_role("textbox", name="name@example.com").press("Alt+ControlOrMeta+@")
    page.get_by_role("textbox", name="name@example.com").press("Alt+6")
    page.get_by_role("textbox", name="name@example.com").press("Alt+4")
    page.get_by_role("textbox", name="name@example.com").fill("odchantre@hotmail.com")
    page.get_by_text("Male", exact=True).click()
    page.get_by_role("textbox", name="Mobile Number").click()
    page.get_by_role("textbox", name="Mobile Number").fill("3167485525")
    page.locator("#dateOfBirthInput").click()
    page.get_by_role("option", name="Choose Monday, August 4th,").click()
    page.locator(".subjects-auto-complete__value-container").click()
    page.locator("#subjectsInput").fill("prueba")
    page.get_by_text("Sports").click()
    page.get_by_role("textbox", name="Current Address").click()
    page.get_by_role("textbox", name="Current Address").fill("prueba")
    page.locator("div").filter(has_text=re.compile(r"^Select State$")).nth(3).click()
    page.get_by_text("Haryana", exact=True).click()
    page.get_by_text("Select City").click()
    page.get_by_text("Panipat", exact=True).click()
    page.get_by_role("button", name="Submit").click()
    page.get_by_role("button", name="Close").click()
