import re
from playwright.sync_api import Page, expect


def test_example(page: Page) -> None:
    page.goto("https://demoqa.com/")
    page.locator("svg").first.click()
    page.locator("span").filter(has_text="Forms").locator("div").first.click()
    page.get_by_text("Practice Form").click()
    page.get_by_role("textbox", name="First Name").click()
    page.get_by_role("textbox", name="First Name").fill("Juan")
    page.get_by_role("textbox", name="First Name").press("Tab")
    page.get_by_role("textbox", name="Last Name").fill("Perez")
    page.get_by_role("textbox", name="name@example.com").click()
    page.get_by_role("textbox", name="name@example.com").fill("PerezJuan")
    page.get_by_role("textbox", name="name@example.com").press("Alt+6")
    page.get_by_role("textbox", name="name@example.com").press("Alt+4")
    page.get_by_role("textbox", name="name@example.com").fill("PerezJuan@gmail.com")
    page.get_by_text("Male", exact=True).click()
    page.get_by_role("textbox", name="Mobile Number").click()
    page.get_by_role("textbox", name="Mobile Number").fill("3168599965")
    page.locator("#dateOfBirthInput").click()
    page.get_by_role("combobox").nth(1).select_option("1991")
    page.locator("div").filter(has_text=re.compile(r"^JanuaryFebruaryMarchAprilMayJuneJulyAugustSeptemberOctoberNovemberDecember$")).get_by_role("combobox").select_option("2")
    page.get_by_role("option", name="Choose Saturday, March 2nd,").click()
    page.locator(".subjects-auto-complete__value-container").click()
    page.locator("#subjectsInput").fill("Esto es una prueba")
    page.get_by_text("Sports").click()
    page.get_by_role("textbox", name="Current Address").click()
    page.get_by_role("textbox", name="Current Address").fill("Juan esta probando hoy")
    page.get_by_text("Select State").click()
    page.get_by_text("NCR", exact=True).click()
    page.get_by_text("Select City").click()
    page.get_by_text("Delhi", exact=True).click()
    page.get_by_role("button", name="Submit").click()
    page.get_by_role("button", name="Close").click()
